# OpenAI API Key (required for the chatbot)
OPENAI_API_KEY = "your_openai_api_key_here"

# Database credentials (if applicable)
[database]
username = "your_db_username"
token = "your_db_token"

# Additional secrets section
[some_section]
some_key = "1234" 